#!/usr/bin/env python
from os import system, listdir, walk
from os.path import exists, isfile, join, expanduser
from random import choice
from PIL import Image
from json import load, dump
import argparse


ap = argparse.ArgumentParser()
ap.add_argument("--sfw",   required=False, help="Safe for work mode. Choose another background image", action='store_true')
ap.add_argument("--left",  required=False, help="Move image cropout area to the left (or down in album mode)", action='store_true')
ap.add_argument("--right", required=False, help="Move image cropout area to the right (or up in album mode)", action='store_true')
args = vars(ap.parse_args())

# This script expects you to have a lot of your favourite wallpapers in "~/Pictures/wallpapers/JINX"
# and an image for work mode
wallpaper_directory = expanduser("~/Pictures/wallpapers/JINX");
sfw_wallpaper_image = expanduser("~/Pictures/wallpapers/cosmic-cliffs.png");
cache_directory = expanduser("~/.cache")

data_file_path = join(wallpaper_directory, "wallpaper_info.json") 
if exists(data_file_path):
    with open(data_file_path, "r") as file:
        data = load(file)
else:
    data = {
            "path": "",
            "adjustments": {}
            }

# calculate dimensions of all screens together
def calculate_wallpaper_geometry(monitors):
    hor = 0
    ver = 0
    for monitor in monitors:
        hor = max(hor, monitor[0] + monitor[2])
        ver = max(ver, monitor[1] + monitor[3])
    return (hor, ver)

# This script expects you to have wallpapers in "~/Pictures/wallpapers"
wallpaper_directory = expanduser("~/Pictures/wallpapers/JINX");
sfw_wallpaper_image = expanduser("~/Pictures/wallpapers/cosmic-cliffs.png");

all_images = []
if args["sfw"]:
     all_images.append(sfw_wallpaper_image)   
elif not args["left"] and not args["right"]:
    for root, dirs, files in walk(wallpaper_directory):
        for image in files:
            if isfile(join(root, image)):
                if image.lower().endswith((".png", ".jpg")):
                    all_images.append(join(root, image))
    
# Set geometry of your monitors [offset_x, offset_y, width, height]
monitors = [
    [0,     0,  1920,   1080],
]

# create wallpaper and paste images to it
wallpaper = Image.new('RGB', calculate_wallpaper_geometry(monitors), (0, 0, 0))

for index, monitor in enumerate(monitors):
    path = ""
    if args["left"]:
        path = data["path"]
        if path in data["adjustments"].keys():
            data["adjustments"][path] -= 10
        else:
            data["adjustments"][path] = -10
    elif args["right"]:
        path = data["path"]
        if path in data["adjustments"].keys():
            data["adjustments"][path] += 10
        else:
            data["adjustments"][path] = 10
    else:
        path = choice(all_images)
    
    data["path"] = path
    image = Image.open(path) # load random wallpaper
    adjustment = 0
    if path in data["adjustments"].keys():
        adjustment = data["adjustments"][path]
   
    print(adjustment, path)
    width, height = image.size
    if width >= height / 9 * 16:
        # Change width
        trail = width - height / 9 * 16
        image = image.crop((trail / 2 + adjustment, 0, width - trail / 2 + adjustment, height)) 
    else:
        # Change height
        trail = height - width / 16 * 9
        image = image.crop((0, trail / 2 + adjustment, width, height - trail / 2 + adjustment))

    image = image.resize((monitor[2], monitor[3]))
    wallpaper.paste(image, (monitor[0], monitor[1]))

# save wallpaper to cache and run feh
wallpaper.save(join(cache_directory, "screen_wallpaper.jpg"), "JPEG")
system(f"feh --no-xinerama --bg-fill {join(cache_directory, 'screen_wallpaper.jpg')}")

with open(data_file_path, "w") as file:
    dump(data, file, sort_keys=True, indent=4)
